#' @title BCscTool															
#' @description The present function associates the clusters of two different and indipendent experiments using the Bray Curtis dissimilarity. BOTH set must have same number and name of ROW (GENES)	
#' @param group, a character string. Two options: sudo or docker, depending to which group the user belongs					
#' @param scratch.folder, a character string indicating the path of the scratch folder
#' @param setA, path to the first dataset
#' @param setAclustering, path to the clustering file for the first dataset. This file is derived from clustering.output file generated by the rCASC clustering. It contains the following columns: CellName, Belonging_Cluster
#' @param markerA, path to the file containing cluster specific genes for the first dataset. The file requires the following column: gene, cluster
#' @param setB, path to the second dataset
#' @param setBclustering, path to the clustering file for the second dataset. This file is derived from clustering.output file generated by the rCASC clustering. It contains the following columns: CellName, Belonging_Cluster
#' @param markerB, path to the file containing cluster specific genes for the second dataset. The file requires the following column: gene, cluster
#' @param separator, separator used in both count file, e.g. ','
#' @param contamination, fraction of genes to be contaminated at each eprmutaitone DEFAULT VALUE: 5
#' @param permutation, number of permutations DEFAULT VALUE: 50
#' @param threshold, minimum value to consider a gene expressed in both count sets. DEFAULT VALUE: 3
#' @author Gabriele Piacenti, g [dot] pia91 [at] gmail [dot] com, University of Torino
#'
#' @return 
#' @examples			
#' \dontrun{
#' BCscTool(group = "docker",
#'          scratch.folder = "/home/user09/piacenti/ProvaBCSC/scratch",
#'          setA = paste(getwd(),"setA.csv",sep = "/"),
#'          setAclustering = paste(getwd(),"setA_clustering.csv",sep = "/"),
#'          markerA = paste(getwd(),"setA.markers.csv",sep = "/"),
#'          setB =paste(getwd(),"set1.csv",sep = "/"),
#'          setBclustering = paste(getwd(),"set1_clustering.csv",sep = "/"),
#'          markerB =paste(getwd(),"set1.markersPROVA.csv",sep = "/"),
#'          separator =",",
#'          contamination = 10 ,
#'          permutation = 10,
#'          threshold = 3 )
#' }
#' @export
BCscTool <- function(group=c("sudo","docker"),
                     scratch.folder, 
                     setA, 
                     setAclustering, 
                     markerA, 
                     setB, 
                     setBclustering, 
                     markerB, 
                     separator, 
                     contamination = 5, 
                     permutation = 50,
                     threshold = 3){

data.folder=dirname(setA)
positions=length(strsplit(basename(setA),"\\.")[[1]])
matrixNameC=strsplit(basename(setA),"\\.")[[1]]
matrixName=paste(matrixNameC[seq(1,positions-1)],collapse="")
format=strsplit(basename(basename(setA)),"\\.")[[1]][positions]


## da qui fino a segno *** NON TOCCARE

  #running time 1
  ptm <- proc.time()
  #setting the data.folder as working folder
  if (!file.exists(data.folder)){
    cat(paste("\nIt seems that the ",data.folder, " folder does not exist\n"))
    return(2)
  }

  #storing the position of the home folder
  home <- getwd()
  setwd(data.folder)
  #initialize status
  system("echo 0 > ExitStatusFile 2>&1")

  #testing if docker is running
  test <- dockerTest()
  if(!test){
    cat("\nERROR: Docker seems not to be installed in your system\n")
    system("echo 10 > ExitStatusFile 2>&1")
    setwd(home)
    return(10)
  }


  #check  if scratch folder exist
  if (!file.exists(scratch.folder)){
    cat(paste("\nIt seems that the ",scratch.folder, " folder does not exist\n"))
    system("echo 3 > ExitStatusFile 2>&1")
    setwd(data.folder)
    return(3)
  }
  
  tmp.folder <- gsub(":","-",gsub(" ","-",date()))
  scrat_tmp.folder=file.path(scratch.folder, tmp.folder)
  writeLines(scrat_tmp.folder,paste(data.folder,"/tempFolderID", sep=""))
  cat("\ncreating a folder in scratch folder\n")
  dir.create(file.path(scrat_tmp.folder))
  #preprocess matrix and copying files

if(separator=="\t"){
separator="tab"
}

#### ***

system(paste("cp ",
             setA," ",
             setAclustering, " ",
             markerA, " ",
             setB," ",
             setBclustering," ",
             markerB," ",
             scrat_tmp.folder,"/",
             sep="")
       )

  #executing the docker job   VA CAMBIATO  CON IL COMANDO PER LANCIARE IL DOCKER
params <- paste("--cidfile ",data.folder,"/dockerID -v ",scrat_tmp.folder,
                ":/scratch -d repbioinfo/bcsctemp Rscript /home/BCscTool.R ",
                basename(setA)," ", 
                basename(setAclustering)," ",
                basename(markerA), " ",
                basename(setB)," ", 
                basename(setBclustering)," ", 
                basename(markerB)," ",
                separator," ", 
                contamination," ",
                permutation," ",
                threshold, sep = "")

    
############################ DA QUI NON TOCCO FINO A SEGNO ***
    
resultRun <- runDocker(group=group, params=params)

  #waiting for the end of the container work
  if(resultRun==0){
    #system(paste("cp ", scrat_tmp.folder, "/* ", data.folder, sep=""))
  }
  #running time 2
  ptm <- proc.time() - ptm
  dir <- dir(data.folder)
  dir <- dir[grep("run.info",dir)]
  if(length(dir)>0){
    con <- file("run.info", "r")
    tmp.run <- readLines(con)
    close(con)
    tmp.run[length(tmp.run)+1] <- paste("user run time mins ",ptm[1]/60, sep="")
    tmp.run[length(tmp.run)+1] <- paste("system run time mins ",ptm[2]/60, sep="")
    tmp.run[length(tmp.run)+1] <- paste("elapsed run time mins ",ptm[3]/60, sep="")
    writeLines(tmp.run,"run.info")
  }else{
    tmp.run <- NULL
    tmp.run[1] <- paste("run time mins ",ptm[1]/60, sep="")
    tmp.run[length(tmp.run)+1] <- paste("system run time mins ",ptm[2]/60, sep="")
    tmp.run[length(tmp.run)+1] <- paste("elapsed run time mins ",ptm[3]/60, sep="")

    writeLines(tmp.run,"run.info")
  }

  #saving log and removing docker container
  container.id <- readLines(paste(data.folder,"/dockerID", sep=""), warn = FALSE)
  system(paste("docker logs ", substr(container.id,1,12), " &> ",data.folder,"/",
               substr(container.id,1,12),".log", sep=""))
  system(paste("docker rm ", container.id, sep=""))


  #Copy result folder
  cat("Copying Result Folder")
  system(paste("cp -r ",scrat_tmp.folder,"/* ",data.folder,sep=""))
  #removing temporary folder
  cat("\n\nRemoving the temporary file ....\n")
  system(paste("rm -R ",scrat_tmp.folder))
  system("rm -fR out.info")
  system("rm -fR dockerID")
  system("rm  -fR tempFolderID")
  system(paste("cp ",paste(path.package(package="rCASC"),"containers/containers.txt",sep="/")," ",
               data.folder, sep=""))
  setwd(home)
}

########################################################################################## ****
