#' @title Executing clustering with griph. 
#' @description This function executes a ubuntu docker that produces a specific number of permutations using griph as clustering tool.
#' @param group, a character string. Two options: sudo or docker, depending to which group the user belongs
#' @param scratch.folder, a character string indicating the path of the scratch folder
#' @param file, a character string indicating the path of the file, with file name and extension included
#' @param nPerm, number of permutations to be executed
#' @param permAtTime, number of permutations computed in parallel
#' @param percent, percentage of randomly selected cells removed in each permutation
#' @param separator, separator used in count file, e.g. '\\t', ','
#' @param logTen, 1 if the count matrix is already in log10, 0 otherwise
#' @param perplexity, number of close neighbors for each point. This parameter is specific for tSne. Default value is 10.. The performance of t-SNE is fairly robust under different settings of the perplexity. The most appropriate value depends on the density of your data.  A larger/denser dataset requires a larger perplexity. Typical values for the perplexity range between 5 and 50
#' @param seed, important value to reproduce the same results with same input
#' @param format, output file format csv or txt. Only required if sparse matrix is used

#' @author Luca Alessandri, alessandri [dot] luca1991 [at] gmail [dot] com, University of Torino
#'
#' @return A folder Results containing a folder with the name of the experiment, which contains: VioPlot of silhouette cells value for each number of cluster used, a folder with the number of clusters used for SIMLR clustering, which contains: clusterP file with clustering results for each permutation, killedCell file with removed cells in each permutation, clustering.output a sommarize file with general information for each cells
#' @examples
#' \dontrun{
#' system("wget http://130.192.119.59/public/section4.1_examples.zip")
#' unzip("section4.1_examples.zip")
#' setwd("section4.1_examples")
#' griphBootstrap(group="docker",scratch.folder="/data/scratch/",
#'                file=paste(getwd(), "bmsnkn_5x100cells.txt", sep="/"), 
#'                nPerm=160, permAtTime=8, percent=10, separator="\t",logTen=0, 
#'                seed=111, format="NULL")
#'}
#' @export

griphBootstrap <- function(group=c("sudo","docker"), scratch.folder, file, nPerm, permAtTime, percent, separator, logTen=0, perplexity=10, seed=111, format=NULL){

 
   permutationClustering(group=group, scratch.folder=scratch.folder, file=file, nPerm=nPerm, permAtTime=permAtTime, percent=percent, separator=separator, seed=seed, logTen=logTen, clustering="griph", perplexity=perplexity)
   if(separator == ","){
     matrixName=strsplit(file,"/")[[1]][length(strsplit(file,"/")[[1]])]
     matrixName <- sub(".csv$", "", matrixName)
   }else{
     matrixName=strsplit(file,"/")[[1]][length(strsplit(file,"/")[[1]])]
     matrixName <- sub(".txt$", "", matrixName)
   }
   cluster.path <- paste(data.folder=dirname(file), "Results", matrixName, sep="/")
   
   cluster <- as.numeric(list.dirs(cluster.path, full.names = FALSE, recursive = FALSE))
    if(length(cluster)==1){
         permAnalysisSeurat(group=group, scratch.folder=scratch.folder,file=file, nCluster=cluster, separator=separator, sp=0.8,sparse=FALSE,format=format)
    } else{
       cat("\nIt seems that there is more than one cluster folders in the output of seuratPermutation\n")
       cat("Check the results generated by permutationClustering, and run permAnalysisSeurat selecting the cluster of interest\n")
       system("echo 5 > ExitStatusFile 2>&1")
       return(5)
    }
  
} 
