#' @title Executing clustering with Seurat
#' @description This function executes a ubuntu docker that produces a specific number of permutations using Seurat as clustering tool.
#' @param group, a character string. Two options: sudo or docker, depending to which group the user belongs
#' @param scratch.folder, a character string indicating the path of the scratch folder
#' @param file, a character string indicating the path of the file, with file name and extension included
#' @param nPerm, number of permutations to be executed
#' @param permAtTime, number of permutations computed in parallel
#' @param percent, percentage of randomly selected cells removed in each permutation
#' @param separator, separator used in count file, e.g. '\\t', ','
#' @param logTen, 1 if the count matrix is already in log10, 0 otherwise
#' @param pcaDimensions, PCs threshold selected using seuratPCAEval function.
#' @param seed, important value to reproduce the same results with same input
#' @param sparse, boolean for sparse matrix.  A sparse matrix is a format that reduces the size of the matrix, considering only positions different from 0. The format supported in rCASC is the one generated by 10XGenomics output: genes.tsv, barcodes.tsv and matrix.tbx. 
#' @param format, output file format csv or txt. Only required if sparse matrix is used

#' @author Luca Alessandri, alessandri [dot] luca1991 [at] gmail [dot] com, University of Torino
#'
#' @return A folder Results containing a folder with the name of the experiment, which contains: VioPlot of silhouette cells value for each number of cluster used, a folder with the number of clusters used for SIMLR clustering, which contains: clusterP file with clustering results for each permutation, killedCell file with removed cells in each permutation, clustering.output a sommarize file with general information for each cells
#' @examples
#' \dontrun{
#' system("wget http://130.192.119.59/public/section4.1_examples.zip")
#' unzip("section4.1_examples.zip")
#' setwd("section4.1_examples")
#' seuratBootstrap(group="docker",scratch.folder="/data/scratch/",file=paste(getwd(), "bmsnkn_5x100cells.txt", sep="/"), nPerm=160, permAtTime=8, percent=10, separator="\t",logTen=0, pcaDimensions=6, seed=111, sparse=FALSE,format="NULL")
#'}
#' @export

seuratBootstrap <- function(group=c("sudo","docker"), scratch.folder, file, nPerm, permAtTime, percent, separator, logTen=0, pcaDimensions, seed=111,sparse=FALSE,format="NULL"){

  if(!sparse){
  seuratPermutation(group=group, scratch.folder=scratch.folder, file=file, nPerm=nPerm, permAtTime=permAtTime, percent=percent, separator=separator, logTen=logTen, pcaDimensions=pcaDimensions, seed=seed)
  cluster.path <- paste(data.folder=dirname(file), "Results", strsplit(basename(file),"\\.")[[1]][1], sep="/")
  cluster <- as.numeric(list.dirs(cluster.path, full.names = FALSE, recursive = FALSE))
  if(length(cluster)==1){
    permAnalysisSeurat(group=group, scratch.folder=scratch.folder,file=file, nCluster=cluster, separator=separator, sp=0.8)
  } else{
    cat("\nIt seems that there is more than one cluster folders in the output of seuratPermutation\n")
    cat("Check the results generated by seuratPermutation, and run permAnalysisSeurat selecting the cluster of interest\n")
    system("echo 5 > ExitStatusFile 2>&1")
    return(5)
  }
    
  }else{
  
    seuratPermutation(group=group, scratch.folder=scratch.folder, file=file, nPerm=nPerm, permAtTime=permAtTime, percent=percent, separator=separator, logTen=logTen, pcaDimensions=pcaDimensions, seed=seed,sparse,format=format)
   matrixName=strsplit(dirname(file),"/")[[1]][length(strsplit(dirname(file),"/")[[1]])]
data.folder=paste(strsplit(dirname(file),"/")[[1]][-length(strsplit(dirname(file),"/")[[1]])],collapse="/")
cluster.path <- paste(data.folder=data.folder, "Results",strsplit(dirname(file),"/")[[1]][length(strsplit(dirname(file),"/")[[1]])], sep="/")
    
    

    cluster <- as.numeric(list.dirs(cluster.path, full.names = FALSE, recursive = FALSE))
  if(length(cluster)==1){
    permAnalysisSeurat(group=group, scratch.folder=scratch.folder,file=file, nCluster=cluster, separator=separator, sp=0.8,sparse=sparse,format=format)
  } else{
    cat("\nIt seems that there is more than one cluster folders in the output of seuratPermutation\n")
    cat("Check the results generated by seuratPermutation, and run permAnalysisSeurat selecting the cluster of interest\n")
    system("echo 5 > ExitStatusFile 2>&1")
    return(5)
  }
  
  
  
  
  
  
  
  }

}

